import { FileOps } from "@laoban/fileops";
import { NameAnd } from "@laoban/utils";
import { CatalogData, ModuleData } from "../module";
import { defaultMakeCatalogFromArray, defaultMakeCatalogFromCD, FileType, SimpleFileType } from "./filetypes";
import { Policy } from "../policy";

export const catalogInfoYamlTC: SimpleFileType = {
  sourceType: 'catalogdata',
  match: ( filename: string ) => filename === 'catalog-info.yaml',
  load: async ( fileOps: FileOps, policy: Policy, pathOffset: string, filename: string, debug?: boolean ) : Promise<CatalogData> => {
    const value = await fileOps.loadFileOrUrl ( filename );
    const ignore = value.startsWith ( "# Autogenerated" )
    return { catalogData: true, sourceType: 'catalogdata', catalogName: pathOffset, pathOffset, value, ignore, existingGenerated: ignore }
  },
  makeCatalogFromMd: defaultMakeCatalogFromCD
}