import { FileOps } from "@laoban/fileops";
import { NameAnd } from "@laoban/utils";
import { ModuleData } from "../module";
import { defaultMakeCatalog, FileType } from "./filetypes";

export const catalogInfoYamlTC: FileType = {
  sourceType: 'catalogdata',
  match: ( filename: string ) => filename === 'catalog-info.yaml',
  load: async ( fileOps: FileOps, pathOffset: string, filename: string, debug?: boolean ) => {
    const value = await fileOps.loadFileOrUrl ( filename );
    const ignore = value.startsWith ( "# Autogenerated" )
    return { catalogData: true, sourceType: 'catalogdata', catalogName: pathOffset, pathOffset, value, ignore }
  },
  makeArray: ( trees, entityToMd: NameAnd<ModuleData> ) => ( md: ModuleData ) => [ md ],
  makeCatalog: defaultMakeCatalog
}